# Generated by Django 3.0.8 on 2020-07-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
